{
  "version": 2,
  "updates": [
    {
      "package-ecosystem": "github-actions",
      "directory": "/",
      "schedule": {
        "interval": "weekly",
        "day": "monday",
        "time": "06:00",
        "timezone": "Europe/Paris"
      },
      "open-pull-requests-limit": 5,
      "labels": ["dependencies", "ecosystem:github-actions"],
      "groups": {
        "ordinary-github-actions": {
          "applies-to": "version-updates",
          "patterns": ["*"],
          "update-types": ["minor", "patch"]
        }
      }
    }
  ]
}
