sonar.projectKey=robintrassard_perf-sentinel-jetbrains-plugin-jvm
sonar.projectName=Perf Sentinel JetBrains Plugin JVM
sonar.sourceEncoding=UTF-8
sonar.sources=src/main/kotlin,protocol/src/main/kotlin,rider-frontend/src/main/kotlin
sonar.tests=src/test/kotlin,rider-frontend/src/test/kotlin
sonar.exclusions=build/**,protocol/build/**,rider-frontend/build/**
sonar.coverage.jacoco.xmlReportPaths=build/reports/kover/report.xml
sonar.junit.reportPaths=build/test-results/test,build/test-results/testGoLand253,build/test-results/testPhpStorm253,build/test-results/testPyCharm253,build/test-results/testRubyMine253,build/test-results/testRustRover253,build/test-results/testRustRover262,build/test-results/testWebStorm253,rider-frontend/build/test-results/test
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=600
