import importlib.util
import tempfile
import unittest
from pathlib import Path

RELOCK = Path(__file__).parents[1] / "ci" / "relock.py"


def load_relock():
    spec = importlib.util.spec_from_file_location("relock", RELOCK)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


METADATA = """<?xml version="1.0" encoding="UTF-8"?>
<verification-metadata>
   <components>
      <component group="a.b" name="lib" version="1.2">
         <artifact name="lib-1.2.jar">
            <sha256 value="old" origin="Generated by Gradle"/>
         </artifact>
      </component>
      <component group="c.d" name="tool" version="2.0">
         <artifact name="tool-2.0.jar">
            <sha256 value="kept" origin="Generated by Gradle"/>
         </artifact>
      </component>
   </components>
</verification-metadata>
"""


class RelockTest(unittest.TestCase):
    def setUp(self):
        self.relock = load_relock()
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)

    def test_reads_both_shapes_of_a_lenient_failure(self):
        output = (
            "One artifact failed verification: pycharm-2025.3.6.1.tar.gz (python:pycharm:2025.3.6.1) from repository JetBrains IDE Installers\n"
            "2 artifacts failed verification:\n"
            "  - jsoup-1.23.1.jar (org.jsoup:jsoup:1.23.1) from repository Gradle Central Plugin Repository\n"
            "  - netty-bom-4.2.16.Final.pom (io.netty:netty-bom:4.2.16.Final) from repository Gradle Central Plugin Repository\n"
        )
        self.assertEqual(
            [
                ("python", "pycharm", "2025.3.6.1", "pycharm-2025.3.6.1.tar.gz"),
                ("org.jsoup", "jsoup", "1.23.1", "jsoup-1.23.1.jar"),
                ("io.netty", "netty-bom", "4.2.16.Final", "netty-bom-4.2.16.Final.pom"),
            ],
            self.relock.missing_artifacts(output),
        )

    def test_hashes_the_cached_copy_or_the_local_one_a_platform_repository_resolved(self):
        home = self.root / "home"
        cached = home / "caches/modules-2/files-2.1/org.jsoup/jsoup/1.23.1/abc/jsoup-1.23.1.jar"
        cached.parent.mkdir(parents=True)
        cached.write_bytes(b"jsoup")
        local = self.root / "ide/lib/app.jar"
        local.parent.mkdir(parents=True)
        local.write_bytes(b"app")
        output = (
            "  - jsoup-1.23.1.jar (org.jsoup:jsoup:1.23.1) from repository Gradle Central Plugin Repository\n"
            "  - app.jar (bundledModule:runtime:GO-253.1) from repository localPlatformArtifacts\n"
            f"relock-artifact bundledModule:runtime:GO-253.1 {local}\n"
        )
        checksums = {}
        self.relock.collect(home, output, checksums)
        self.assertEqual(
            {("org.jsoup", "jsoup", "1.23.1"): {"jsoup-1.23.1.jar": self.relock.sha256(cached)},
             ("bundledModule", "runtime", "GO-253.1"): {"app.jar": self.relock.sha256(local)}},
            checksums,
        )

    def test_adds_checksums_in_order_and_never_rewrites_one(self):
        metadata = self.root / "verification-metadata.xml"
        metadata.write_text(METADATA, encoding="utf-8")
        added = self.relock.insert(metadata, {
            ("c.d", "tool", "2.0"): {"tool-2.0.jar": "rewritten", "tool-2.0.pom": "pom"},
            ("b.c", "new", "1.10"): {"new-1.10.jar": "new"},
            ("a.b", "lib", "1.10"): {"lib-1.10.jar": "lib"},
        })
        text = metadata.read_text(encoding="utf-8")
        self.assertEqual(3 + 1 - 1, added)
        self.assertIn('value="kept"', text)
        self.assertNotIn('value="rewritten"', text)
        order = [line.strip() for line in text.splitlines() if "<component " in line]
        self.assertEqual([
            '<component group="a.b" name="lib" version="1.2">',
            '<component group="a.b" name="lib" version="1.10">',
            '<component group="b.c" name="new" version="1.10">',
            '<component group="c.d" name="tool" version="2.0">',
        ], order)
        self.assertLess(text.index('name="tool-2.0.jar"'), text.index('name="tool-2.0.pom"'))

    def test_groups_come_from_each_projects_lock(self):
        (self.root / "gradle.lockfile").write_text(
            "a:b:1=compileClasspath,intellijPlatformTestClasspath_testGoLand253\nempty=runtimeClasspath_runRider\n",
            encoding="utf-8",
        )
        (self.root / "settings.gradle.kts").write_text('include(":frontend")\n', encoding="utf-8")
        for directory in ("frontend", "tooling"):
            (self.root / directory).mkdir()
            (self.root / directory / "gradle.lockfile").write_text("a:b:1=compileClasspath\n", encoding="utf-8")
        self.assertEqual(
            [("", ""), ("", "runRider"), ("", "testGoLand253"), (":frontend", "")],
            self.relock.groups(self.root),
        )


if __name__ == "__main__":
    unittest.main()
